### PR TITLE
color contrast in code in notecard && note

### PR DESCRIPTION
**Pull request by mattiapontonio**
https://github.com/mdn/yari/issues/2662

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
I'd avoid to use a direct colour, but instead add a variable to https://github.com/mdn/mdn-minimalist/blob/e035e3fbcf43d1d852864dfa0ee2a00d31418e6a/sass/vars/_color-palette.scss if needed.
This way, you do not diverge from a colour palette (branding).

I can't tell off-hand, which colour the respective variables translate to (not cloned the minimalist repo locally).

**Comment by mattiapontonio** [comment]
@Ryuno-Ki me too but if You want to suggest a random color a i can commit and see of the CI of color contrast passes (that i don't think exists on the earth)

**Comment by Ryuno-Ki** [comment]
color-palette1
color-palette2

`$neutral-100` or `$neutral-200` seem apt.
Check with usage on other parts if needed (I'm missing comments on usage in that file, but that's outside of this repo. Perhaps a use case for http://sassdoc.com/ ?)

**Comment by mattiapontonio** [comment]
> Perhaps a use case for http://sassdoc.com/ ?)
I'm from _less_ and not more... 🤷🏻‍♂️🙂

I'm taking a pause from this issue 🙂

**Comment by mattiapontonio** [comment]
@Ryuno-Ki how I can Mark You as co author here?

**Comment by Ryuno-Ki** [comment]
Um, you don't have a local setup?
Let me know the commit you want to add me to and I'll do it then.

**Comment by mattiapontonio** [comment]
> Um, you don't have a local setup?

Nope.

The commit Is:
https://github.com/mdn/mdn-minimalist/commit/923e15ae9671cf4c60a2ab95d782a4b22495ce20

The suggestion of using a variable...
_Anyway I will try again to boycott this thing of the variables._

**Comment by Ryuno-Ki** [comment]
Hmm … would you be willing to let me open the PR?
https://github.com/mdn/mdn-minimalist/compare/main...Ryuno-Ki:co-author-pr?expand=1 shows us both for the last commit.

**Comment by mattiapontonio** [comment]
Nice solution without have privilages here 👍

**Pull request closed without merging**
