### PR TITLE
remove border-left property for th,td :first-child

### PR DESCRIPTION
**Pull request by AnilSeervi**
Fixes mdn/content#7780

### CODE REVIEW

**Comment by sideshowbarker** [comment]
@AnilSeervi You should edit the issue description to read “Fixes mdn/content#7780” — because GitHub auto-recognizes “Fixes #NNNN” as a “fixes this issue #NNNN” statement (and so will auto-link the two issues), but doesn’t auto-recognize “Fix for #NNNN”.

**Comment by AnilSeervi** [comment]
@sideshowbarker Edit done.
Thanks for the info.

**Review by schalkneethling — APPROVED** [review]
Apologies for the delay @AnilSeervi - this looks good.

**Comment by AnilSeervi** [comment]
This change is not live yet. Many of the pages still have same old weird table border issue @schalkneethling
Is this because there hasn't been any new [releases](https://github.com/mdn/mdn-minimalist/releases/) recently.

**Comment by schalkneethling** [comment]
> This change is not live yet. Many of the pages still have same old weird table border issue @schalkneethling Is this because there hasn't been any new [releases](https://github.com/mdn/mdn-minimalist/releases/) recently.

Indeed. I will take care of that today. Thank you for the nudge.

**Pull request merged**
