### PR TITLE
color contrast in code in notecard && note

### PR DESCRIPTION
**Pull request by mattiapontonio**
- https://github.com/mdn/mdn-minimalist/pull/444

Fixes: https://github.com/mdn/yari/issues/2662

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
Replaces #444 (like @mattiapontonio linked). See discussion there.

**Comment by schalkneethling** [comment]
Hey, @mattiapontonio and @Ryuno-Ki - Thank you for the pull request however, this only fixes one specific instance of this problem. It also occurs in other contexts on the pages as well so, we need to identify all of those, and then provide a single solution to the larger problem.

**Comment by mattiapontonio** [comment]
It was still wrong because you had to act on the link.

**Comment by Ryuno-Ki** [comment]
@mattiapontonio Could you reopen? I'd look after the other instances and update this PR. Thanks.

**Comment by mattiapontonio** [comment]
@Ryuno-Ki 
Please read @schalkneethling.
Probably this Is completely wrong (not on link, not on pseudo classes, not global, maybe not the right color).
Sorry for the _loosed work_.
What We need here is talking about that, don't worry about making PRs.

**Comment by Ryuno-Ki** [comment]
@mattiapontonio I wouldn't have accessed if GitHub would have allowed me to reopen it ;-)

I've read that this PR falls too short. That does not imply to me, that it couldn't be extended to other instances.

**Comment by mattiapontonio** [comment]
Yes sometimes even ti me don't allow to reopen even if there Is the button 🙂

**Pull request closed without merging**
